@startuml derelict_land
!define LIGHTBLUE #E0FFFF

package "derelict_land" {
  package "commands" {
    interface ICommand {
      +CommandExecute()
    }

    class ExitCommand {
      +CommandExecute()
    }

    class ExploreCommand {
      +CommandExecute()
    }

    class NewGame {
      +CommandExecute()
    }

    class OpenShopCommand {
      +CommandExecute()
    }

    class ShowCommandsList {
      +CommandExecute()
    }

    class ShowInventoryCommand {
      +CommandExecute()
    }

    class ShowPlayerStats {
      +CommandExecute()
    }
  }

  package "entity" {
    class Player {
      -Player()
      +CreatePlayer()
    }
    class Enemy {
    }
  }

  package "logic" {
    abstract class DefaultLogic {
      #commands : std::unordered_map<std::string, std::shared_ptr<ICommand>>
      +DefaultLogic()
      +DoCommand(std::string&)
      +GetCommands()
      +AddCommand(std::string, std::shared_ptr<ICommand>)
    }

    class LogicHandler {
      -LogicHandler()
      +LogicHandlerInstance : LogicHandler*
      +GetInstance() : LogicHandler*
      +CurrentLogic : DefaultLogic*
      +ChangeLogic(DefaultLogic*)
    }

    class MainMenuLogic {
      -MainMenuLogic()
      +MainMenuLogicInstance : MainMenuLogic*
      +GetInstance() : MainMenuLogic*
    }

    class TownLogic {
      -TownLogic()
      +TownLogicInstance : TownLogic*
      +GetInstance() : TownLogic*
    }

    class ShopLogic {
      -ShopLogic()
      +ShopLogicInstance : ShopLogic*
      +GetInstance() : ShopLogic*
    }

    class FightLogic {
      -FightLogic()
      +MainFightLogicInstance : FightLogic*
      +GetInstance() : FightLogic*
      +AddEnemy(Enemy*)
      +RemoveEnemy(Enemy*)
      +GetEnemies() : std::vector<Enemy*>
    }
  }

  package "main_game_obj" {
    class GameMaster {
      -GameMaster()
      +instance : GameMaster*
      +GetInstance() : GameMaster*
      +InitializePlayer()
      +GetPlayer() : Player*
      +GetCurrentLogic() : DefaultLogic*
      +SetCurrentLogic(DefaultLogic*)
      +GetDirector() : Director*
    }

    class Director {
      -story_points : int
      +GetStoryPoints() : int
      +SetStoryPoints(int)
    }

    class GameInitialisation {
      +StartGame()
    }
  }
  class UILogic{

  }
}

' Relationships

' Commands
ICommand <|-- ExitCommand
ICommand <|-- ExploreCommand
ICommand <|-- NewGame
ICommand <|-- OpenShopCommand
ICommand <|-- ShowCommandsList
ICommand <|-- ShowInventoryCommand
ICommand <|-- ShowPlayerStats

' Logic
DefaultLogic <|-- MainMenuLogic
DefaultLogic <|-- TownLogic
DefaultLogic <|-- ShopLogic
DefaultLogic <|-- FightLogic

LogicHandler "1" -- "1" DefaultLogic : CurrentLogic
DefaultLogic "1" -- "*" ICommand : commands

' GameMaster
GameMaster "1" -- "1" Player : current_player
GameMaster "1" -- "1" Director : director
GameMaster "1" -- "1" DefaultLogic : current_logic

'FightLogic
FightLogic "1" -- "*" Enemy : enemies

'GameInitialisation
GameInitialisation ..> GameMaster

'MainMenuLogic
MainMenuLogic ..> NewGame

'TownLogic
TownLogic ..> ExploreCommand
TownLogic ..> OpenShopCommand
TownLogic ..> ShowInventoryCommand

'DefaultLogic
DefaultLogic ..> ExitCommand
DefaultLogic ..> ShowCommandsList
DefaultLogic ..> ShowPlayerStats

'UILogic
GameInitialisation ..> UILogic

@enduml
